apiVersion: v1
kind: Service
metadata:
  name: dice-service
  namespace: virtualización
spec:
  selector:
    app: dice-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
